# Generated by Django 2.2.6 on 2019-11-06 00:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend_name', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('roast', models.CharField(max_length=100, null=True)),
                ('flavors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None, verbose_name='Flavor(s)')),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None, verbose_name='Note(s)')),
                ('description', models.TextField(null=True)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('vendor_location', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('vendor_website', models.CharField(max_length=100, null=True)),
                ('vendor_phone', models.CharField(max_length=50, null=True)),
                ('review_date', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
